### ISSUE TITLE
collapse expand listener

### ISSUE THREAD

**Issue by Asykur** [giangpham96/expandable-text#2]
how to listen when the text is collapsed or expanded? i try to add clickListener but is causing the text cannot clicked

**Comment by giangpham96** [comment]
You can access those 2 booleans in the view: `collapsed` and `expanded` or do you want to access the progress as well

**Comment by Asykur** [comment]
i mean i want to listen when text is clicked

**Comment by giangpham96** [comment]
you can also does it
```kotlin
textView.setOnClickListener {
    // your logic here
    ...
    // toggle the state
    toggle()
}
```

**Comment by Asykur** [comment]
thank you
