### ISSUE TITLE
Add support for Api 22 and lower devices.

### ISSUE THREAD

**Issue by egeysn** [giangpham96/expandable-text#3]
We must change getStaticLayout function for api 22 and lower devices. I tried adding new StaticLayout constuructor but it doesn't work properly.

`   private fun getStaticLayout(targetMaxLines: Int, text: CharSequence, textWidth: Int): StaticLayout {
        val maximumLineWidth = textWidth.coerceAtLeast(0)
        val alignment = ALIGN_NORMAL
        val includePadding = true

        return if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.M) {
            StaticLayout.Builder
                .obtain(text, 0, text.length, paint, maximumLineWidth)
                .setIncludePad(false)
                .setMaxLines(targetMaxLines)
                .setAlignment(alignment)
                .setEllipsize(END)
                .setLineSpacing(lineSpacingExtra, lineSpacingMultiplier)
                .build()
        } else {
            StaticLayout(
                text,
                0,
                text.length,
                paint,
                maximumLineWidth,
                alignment,
                lineSpacingMultiplier,
                lineSpacingExtra,
                includePadding,
                END,
                width
            )
        }
    }`

**Comment by giangpham96** [comment]
Fixed by your PR #4
