### ISSUE TITLE
Problems implementing

### ISSUE THREAD

**Issue by alejandrolaverri** [giangpham96/expandable-text#5]
I'm trying to add the 'com.github.giangpham96.expandable-text:expandable_textview:2.0.0' dependency to my project and I get the error "Failed to resolve". I have added in the build.gradle of the project the following line:
allprojects {
     repositories {
         Google()
         maven { url = uri("https://jitpack.io/") }
     }
}

As it appears in the repository's Readme.

**Comment by giangpham96** [comment]
Hello @alejandrolaverri 
May I see your settings.gradle file? Are you using central declaration of repositories there?

If you use it, please move the maven repo declaration there.

Moreover, if you can share the full stacktrace of the issue, that would be helpful

**Comment by alejandrolaverri** [comment]
Hello @giangpham96 
I have added the following declaration in the settings.gradle:
maven { url = uri("https://jitpack.io/") }
And now it works for me.

Thanks for the help.
